async function main() {}

main()
  .then()
  .catch(error => {
    console.log(`Error: ${error}`);
  });
